### ISSUE TITLE
Exits with code 1

### ISSUE THREAD

**Issue by sladec** [kintoandar/fwd#1]
Using it with SSL but it Exits with code 1 every so often.

[Error] readfrom tcp......write: broken pipe
or
[Error] readfrom tcp......read: connection reset by peer
Should it not keep running the process ?

I will wrap it in a upstart job to respawn it on exit for now.

**Comment by kintoandar** [comment]
Thank you for raising this, I'm currently on vacation, with a very poor quality internet access, next week I'll be back home and try to fix the issue.

This is probably due to the go routines raising errors and I was breaking the flow with an exit 1 when that happen.

**Comment by kintoandar** [comment]
The new build `0.1.2` has the patch that fixes this issue, @sladec care to test it out?

**Comment by sladec** [comment]
Thanks
Will give it a test

**Comment by sladec** [comment]
updated, looking good
Thanks
