### ISSUE TITLE
os.Exit() and defer do not work.

### ISSUE THREAD

**Issue by luqasz** [kintoandar/fwd#3]
Hi.

When calling `os.Exit()`, all defers will not be executed. See [example](https://play.golang.org/p/CDiAh9SXRM).

**Comment by kintoandar** [comment]
Hey @luqasz,

Sorry for such late response, I didn't got any notification regarding this issue.
You are right and this needs fixing, will try to pick it up as soon as possible.

Thanks for submitting the issue.
