### ISSUE TITLE
forwarding multiple ports

### ISSUE THREAD

**Issue by hellt** [kintoandar/fwd#5]
Hi @kintoandar !
Thanks for this awesome tool
Do you have plans to add multiple port forwarding support (potentially defined in a file)?

**Comment by kintoandar** [comment]
Hey @hellt ,

It sounds like a good idea, kinda like of ngrok is already doing.
If I have some free time will give it a go 👍

**Comment by hellt** [comment]
Indeed. That what's led me to write this one, recently I played with ngrok
+ fwd (
https://netdevops.me/2020/easily-exposing-your-local-resources-with-ngrok-and-fwd/)
and having to launch many fwd processes was an overkill

**Comment by malaDev** [comment]
@kintoandar I can give a try if you don't mind

**Comment by kintoandar** [comment]
Hey @malaDev , thank you for stepping forward with your help.

I did code all those requirements some time ago but never got around to open the PR, I pushed the changes now, feel free to test them out, they're on the multiport branch.

Once again thank you 🙏
